Controllers/JeuxController.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using SuperBowlWeb.Data;
using SuperBowlWeb.Models;
using SuperBowlWeb.Models.Constantes;
using System.ComponentModel;

namespace SuperBowlWeb.Controllers
{
    
    public class JeuxController : BaseApiController
    {
        private readonly SuperBowlWebContext _context;
        private readonly IMapper _mapper;

        public JeuxController(SuperBowlWebContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        //[AllowAnonymous]
        //[HttpPost]
        //public async Task<ActionResult<Jeu>> CreateMatch(Jeu jeu)
        //{ 
            
        //}



        // GET: Jeux
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var rowsAffected = await _context.Database.ExecuteSqlAsync($"exec changeStatusTable;");
            var superBowlWebContext = await _context.Jeux.Include(m => m.EquipeA).Include(m => m.EquipeB).ToListAsync();
            if (superBowlWebContext == null)
            {
                return NotFound("No entity found in DB ??");
            }
            return Ok(superBowlWebContext);

        }

        [AllowAnonymous]
        [HttpGet]
        [Route("dujour")]
        public async Task<IActionResult> ListMatchDuJour()
        {
            var hier = DateTime.Parse(DateTime.Today.AddDays(-1).ToShortDateString());
            var aujourdui = DateTime.Parse(DateTime.Today.ToShortDateString());
            
            var superBowlWebContext = await _context.Jeux.Where(x => (x.DateRencontre > hier) && (x.DateRencontre <= aujourdui))
                                                            .Include(m => m.EquipeA)
                                                            .Include(m => m.EquipeB)
                                                            .ToListAsync();
            if (superBowlWebContext == null)
            {
                return NotFound("No entity found in DB ??");
            }
            return Ok(superBowlWebContext);
        }
        [AllowAnonymous]
        // Get by id 
        [HttpGet("{id}")]
        public async Task<IActionResult> Details(int id)
        {
            var jeuDetails = await _context.Jeux
                                            .Include(x=>x.EquipeA.Joueurs)
                                            .Include(x => x.EquipeB.Joueurs)
                                            .FirstOrDefaultAsync(x => x.Id == id);
            if (jeuDetails == null)
            {
                return BadRequest("!! Aucun match trouve !!");
            }
            return Ok(jeuDetails);
        }

        private bool MatchExists(int id)
        {
            return (_context.Jeux?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/ParisController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Linq.Expressions;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SuperBowlWeb.Controllers.DTO;
using SuperBowlWeb.Data;
using SuperBowlWeb.Models;

namespace SuperBowlWeb.Controllers
{
    public class ParisController : BaseApiController
    {
        private readonly SuperBowlWebContext _context;
        private readonly Microsoft.AspNetCore.Identity.UserManager<Utilisateur> _userManager;
        private readonly IMapper _mapper;

        public ParisController(SuperBowlWebContext context,UserManager<Utilisateur> userManager, IMapper mapper)
        {
            _context = context;
            _userManager = userManager;
            _mapper = mapper;
        }

        // GET: List de tous les Paris
        public async Task<IActionResult> getId()
        {
            if (_context.Pari.Any())
            {
                var superBowlWebContext = _context.Pari.Select(x=>x.Id).Max();

                return superBowlWebContext == null ? Ok(1): Ok(superBowlWebContext+1);
            }
            return Ok(1);
        
        }
        // GET: List de tous les Paris d un utilisateur
        [HttpGet("byuser/{userId}")]
        public async Task<IActionResult> ListByUserId(string userId)
        {
            if (_context.Pari.Any())
            {
                var parisUser = await _context.Pari.Where(x => x.UserId == userId).Include(x => x.EquipeMise).ToListAsync();
                return Ok(parisUser);
            }
            return NotFound("Pas encore de paris enregistre");
        }

        // GET: Le Paris d un utilisateur sur ce match
        [HttpGet("{email}/bymatch/{matchId}/")]
        public async Task<IActionResult> getByMatchId(int matchId,string email)
        {
            if (_context.Pari.Any())
            {
                if(email != null)
                {
                    var user = await _context.Users.FirstOrDefaultAsync(x => x.Email == email);
                    var pariUser = await _context.Pari.Where(x => x.MatchId == matchId)
                                                        .Where(x=>x.UserId==user.Id)
                                                        .Include(x => x.EquipeMise)
                                                        .Include(x => x.Jeu).ToListAsync();
                    return Ok(pariUser);
                }
                //var pariUser = await _context.Pari.Where(x => x.MatchId == matchId).Include(x => x.EquipeMise).Include(x=>x.Jeu).ToListAsync();
               
            }
            return NotFound("Pas encore de paris enregistre");
        }

        [HttpPost]
        public async Task<IActionResult> Create(Pari pari)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(User.FindFirstValue(ClaimTypes.Email));
                pari.UserId = user.Id;
                
                _context.Pari.Add(pari);
                try
                {
                    await _context.SaveChangesAsync();
                    return Ok(1);
                }catch (Exception ex)
                {
                    return BadRequest(ex.Message);  
                }
            }

            return NotFound(1);
        }

     
        private bool PariExists(int id)
        {
          return (_context.Pari?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperBowlWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SuperBowlWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">*@
            @*<div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SuperBowlWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jeux" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Se Connecter</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Paris" asp-action="Privacy">Parier</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Features</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Pricing</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SuperBowlWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>